name: build

on:
    push: null
    pull_request:
        branches:
          -  master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              uses: "ramsey/composer-install@v1"

            - name: Run test suite
              run: vendor/bin/phpunit
